//! Data types for the cron scheduling subsystem.
//!
//! Defines `CronJob`, `CronJobKind`, `CronJobOrigin`, and
//! `CronJobMetadata` used across repository and scheduler.

use chrono::{DateTime, Utc};

/// Maximum number of agent-originated jobs that may be pending.
pub const AGENT_PENDING_CAP: usize = 5;

/// A single scheduled cron job.
#[derive(Debug, Clone)]
pub struct CronJob {
    /// Unique job identifier.
    pub id: String,
    /// Whether the job is eligible for scheduling.
    pub enabled: bool,
    /// Cron expression (5, 6, or 7 field, or natural language).
    pub expression: String,
    /// Shell command or agent directive to execute.
    pub command: String,
    /// Next scheduled execution time.
    pub next_run: DateTime<Utc>,
    /// Timestamp of the most recent execution, if any.
    pub last_run: Option<DateTime<Utc>>,
    /// Outcome of the most recent execution (e.g. `"ok"`).
    pub last_status: Option<String>,
    /// Whether this job runs a user command or an agent plan.
    pub job_kind: CronJobKind,
    /// Who created this job (user or agent).
    pub origin: CronJobOrigin,
    /// Optional expiration time after which the job is removed.
    pub expires_at: Option<DateTime<Utc>>,
    /// Maximum retry attempts before circuit-breaker opens.
    pub max_attempts: u32,
    /// Running count of consecutive failures.
    pub consecutive_failures: u32,
    /// If set, the circuit breaker is open until this time.
    pub breaker_open_until: Option<DateTime<Utc>>,
}

/// Distinguishes user-command jobs from agent-plan jobs.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum CronJobKind {
    /// A shell command entered by the user.
    User,
    /// An agent plan generated by the AI.
    Agent,
}

impl CronJobKind {
    /// Returns the database string representation.
    pub(crate) fn as_db(self) -> &'static str {
        match self {
            Self::User => "user",
            Self::Agent => "agent",
        }
    }

    /// Parses a database string into a `CronJobKind`.
    pub(crate) fn from_db(value: &str) -> Self {
        if value.eq_ignore_ascii_case("agent") {
            Self::Agent
        } else {
            Self::User
        }
    }
}

/// Who created the cron job.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum CronJobOrigin {
    /// Created by the human operator.
    User,
    /// Created autonomously by the agent.
    Agent,
}

impl CronJobOrigin {
    /// Returns the database string representation.
    pub(crate) fn as_db(self) -> &'static str {
        match self {
            Self::User => "user",
            Self::Agent => "agent",
        }
    }

    /// Parses a database string into a `CronJobOrigin`.
    pub(crate) fn from_db(value: &str) -> Self {
        if value.eq_ignore_ascii_case("agent") {
            Self::Agent
        } else {
            Self::User
        }
    }

    /// Returns `true` if this origin is `Agent`.
    pub(crate) fn is_agent(self) -> bool {
        self == Self::Agent
    }
}

/// Optional metadata attached when creating a cron job.
#[derive(Debug, Clone)]
pub struct CronJobMetadata {
    /// Execution kind (user command vs agent plan).
    pub job_kind: CronJobKind,
    /// Creator of this job.
    pub origin: CronJobOrigin,
    /// Optional expiration timestamp.
    pub expires_at: Option<DateTime<Utc>>,
    /// Maximum retry attempts before circuit-breaker opens.
    pub max_attempts: u32,
}

impl Default for CronJobMetadata {
    fn default() -> Self {
        Self {
            job_kind: CronJobKind::User,
            origin: CronJobOrigin::User,
            expires_at: None,
            max_attempts: 1,
        }
    }
}
