//! OAuth and token import flows for the two supported identity providers.
//!
//! ## Dual-provider abstraction
//!
//! `Asterel` supports two OAuth backends, unified behind the
//! [`OAuthProvider`] enum:
//!
//! - **Codex (`OpenAI`)** — uses the `codex` CLI's device-auth flow. Credentials
//!   are cached in `~/.codex/auth.json`. This path is suitable when the operator
//!   is already a Codex/OpenAI user and has the CLI installed.
//!
//! - **Claude (Anthropic)** — uses a one-time *setup token* (`sk-ant-oat01-…`)
//!   generated by running `claude setup-token` in a separate terminal. The token
//!   is validated locally (prefix + minimum length) before use. There is no
//!   separate refresh token for the Claude path; the setup token itself serves
//!   as the long-lived credential.
//!
//! Both paths produce an [`ImportedOAuthCredential`] with a `target_provider`
//! field that the profile store uses to route API calls to the correct backend.
//!
//! ## Cached vs. interactive import
//!
//! Each provider supports two import modes:
//! - **Cached** (`import_*_cached`): looks for credentials that already exist
//!   on disk or in environment variables without any user interaction. Used
//!   during startup to auto-restore sessions.
//! - **Interactive** (`import_*` / `import_*_setup_token`): runs a CLI flow or
//!   prompts the user to paste a token. Gated behind
//!   [`enforce_spawn_policy`] to prevent unauthorised process spawning.

use std::fs;
use std::io::IsTerminal;
use std::process::{Command, Stdio};

use anyhow::{Context, Result, bail};
use dialoguer::Input;
use directories::UserDirs;
use serde::Deserialize;

use crate::core::providers::catalog::{
    ProviderOAuthFlow, oauth_flow_for_provider, oauth_flow_for_source,
};
use crate::security::{ProcessSpawnClass, SecurityPolicy, enforce_spawn_policy};

const ROUTE_OAUTH_CODEX_LOGIN: &str = "security_auth_oauth_codex_login";
const ROUTE_OAUTH_CODEX_STATUS: &str = "security_auth_oauth_codex_status";
const ROUTE_OAUTH_CLAUDE_STATUS: &str = "security_auth_oauth_claude_status";

const CLAUDE_SETUP_TOKEN_PREFIX: &str = "sk-ant-oat01-";
const CLAUDE_SETUP_TOKEN_MIN_LENGTH: usize = 80;

/// Supported OAuth identity providers.
///
/// ## Security model
///
/// - **`Codex`** — credentials are stored in `~/.codex/auth.json` by the
///   Codex CLI after a device-auth flow. The access token is an `OpenAI` bearer
///   token. `Asterel` reads the file but never writes to it; the CLI owns
///   the credential lifecycle. Interactive login spawns `codex login
///   --device-auth`, which is gated behind [`enforce_spawn_policy`] to ensure
///   the binary is on the operator allow-list before execution.
///
/// - **`Claude`** — credentials are one-time setup tokens issued by the
///   Anthropic `claude` CLI. Tokens have a known prefix (`sk-ant-oat01-`) and
///   minimum length, both of which are validated before the token is accepted.
///   There is no `refresh_token` for Claude setup tokens; re-issuance requires
///   running `claude setup-token` again. Cached credentials are loaded from
///   the `ASTEREL_CLAUDE_SETUP_TOKEN` or `ANTHROPIC_OAUTH_TOKEN`
///   environment variables — never stored on disk by `Asterel`.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub(crate) enum OAuthProvider {
    /// `OpenAI` Codex CLI-based OAuth. Credentials cached in `~/.codex/auth.json`.
    Codex,
    /// Anthropic Claude setup-token-based OAuth. Token validated by prefix and length.
    Claude,
}

impl OAuthProvider {
    /// Parse a provider selector into an `OAuthProvider`.
    ///
    /// # Errors
    ///
    /// Returns an error if the input does not match a known provider.
    pub(crate) fn parse(input: &str) -> Result<Self> {
        match oauth_flow_for_provider(input) {
            Some(ProviderOAuthFlow::Codex) => Ok(Self::Codex),
            Some(ProviderOAuthFlow::Claude) => Ok(Self::Claude),
            _ => {
                bail!("Unsupported OAuth provider '{input}'. Use one of: openai, claude, anthropic")
            }
        }
    }

    fn from_flow(flow: ProviderOAuthFlow) -> Self {
        match flow {
            ProviderOAuthFlow::Codex => Self::Codex,
            ProviderOAuthFlow::Claude => Self::Claude,
        }
    }

    fn parse_source(input: &str) -> Option<Self> {
        oauth_flow_for_source(input).map(Self::from_flow)
    }

    fn import_cached_credential(self) -> Result<Option<ImportedOAuthCredential>> {
        match self {
            Self::Codex => import_codex_oauth_cached(),
            Self::Claude => import_claude_oauth_cached(),
        }
    }

    fn import_interactive_credential(
        self,
        security: &SecurityPolicy,
    ) -> Result<ImportedOAuthCredential> {
        match self {
            Self::Codex => import_codex_oauth(false, security),
            Self::Claude => import_claude_setup_token(None),
        }
    }
}

/// A credential successfully imported from an external OAuth source.
///
/// This struct is the normalised output of all import flows. Callers
/// (typically the profile store or CLI auth commands) use the fields to
/// create or update a provider profile without knowing which underlying
/// flow produced the credential.
pub(crate) struct ImportedOAuthCredential {
    /// Canonical provider name the token authenticates against (e.g.,
    /// `"openai"` or `"anthropic"`). Used to route API calls to the correct
    /// base URL.
    pub(crate) target_provider: &'static str,
    /// Stable profile identifier used when auto-creating a profile entry.
    /// Must be unique per provider; existing profiles with this id are updated
    /// rather than duplicated.
    pub(crate) default_profile_id: &'static str,
    /// Human-readable label shown in the profile selector UI.
    pub(crate) default_label: &'static str,
    /// Short name of the OAuth source that produced the credential (e.g.,
    /// `"codex"`, `"claude"`). Persisted on the profile so that
    /// [`import_cached_oauth_credential_for_source`] can refresh the correct
    /// credential on the next startup.
    pub(crate) source_name: &'static str,
    /// The bearer access token to include in API request headers.
    pub(crate) access_token: String,
    /// Refresh token for renewing the access token without re-authenticating,
    /// if the provider supports it. `None` for Claude setup tokens (no refresh
    /// path — re-issue via `claude setup-token`).
    pub(crate) refresh_token: Option<String>,
}

/// Import Codex (`OpenAI`) OAuth credentials via CLI login flow.
///
/// # Errors
///
/// Returns an error if the Codex CLI login fails or auth file
/// cannot be read.
pub(crate) fn import_codex_oauth(
    skip_cli_login: bool,
    security: &SecurityPolicy,
) -> Result<ImportedOAuthCredential> {
    if !skip_cli_login {
        run_interactive_command(
            "codex",
            &["login", "--device-auth"],
            security,
            ROUTE_OAUTH_CODEX_LOGIN,
        )?;
    }

    let auth_file = load_codex_auth_file()?;
    let access_token = codex_api_credential(&auth_file).ok_or_else(|| {
        anyhow::anyhow!(
            "Codex login succeeded but no OPENAI_API_KEY or access token was found in auth.json"
        )
    })?;
    let refresh_token = codex_refresh_token(&auth_file);

    Ok(ImportedOAuthCredential {
        target_provider: "openai",
        default_profile_id: "openai-oauth-default",
        default_label: "OAuth (codex login)",
        source_name: "codex",
        access_token,
        refresh_token,
    })
}

/// Import cached Codex OAuth credentials without interactive login.
///
/// # Errors
///
/// Returns an error if the auth file exists but cannot be read or parsed.
pub(crate) fn import_codex_oauth_cached() -> Result<Option<ImportedOAuthCredential>> {
    let Some(home_dir) = UserDirs::new().map(|dirs| dirs.home_dir().to_path_buf()) else {
        return Ok(None);
    };
    if !home_dir.join(".codex").join("auth.json").exists() {
        return Ok(None);
    }

    let auth_file = load_codex_auth_file()?;
    let access_token = codex_api_credential(&auth_file);
    let Some(access_token) = access_token else {
        return Ok(None);
    };
    let refresh_token = codex_refresh_token(&auth_file);

    Ok(Some(ImportedOAuthCredential {
        target_provider: "openai",
        default_profile_id: "openai-oauth-default",
        default_label: "OAuth (codex login)",
        source_name: "codex",
        access_token,
        refresh_token,
    }))
}

/// Import a Claude setup token, prompting interactively if needed.
///
/// # Errors
///
/// Returns an error if the token is invalid or interactive input
/// fails.
pub(crate) fn import_claude_setup_token(
    setup_token: Option<String>,
) -> Result<ImportedOAuthCredential> {
    let access_token = if let Some(token) = setup_token {
        normalize_claude_setup_token(&token)?
    } else {
        if !std::io::stdin().is_terminal() {
            bail!(
                "Claude setup-token required in non-interactive mode. \
                 Re-run with --setup-token sk-ant-oat01-..."
            );
        }

        println!();
        println!("Run `claude setup-token` in another terminal, then paste the token below.");
        println!();
        let token: String = Input::new()
            .with_prompt("Paste setup-token (sk-ant-oat01-...)")
            .validate_with(|input: &String| -> Result<(), String> {
                let trimmed = input.trim();
                if trimmed.is_empty() {
                    return Err("Required".into());
                }
                if !trimmed.starts_with(CLAUDE_SETUP_TOKEN_PREFIX) {
                    return Err(format!(
                        "Expected token starting with {CLAUDE_SETUP_TOKEN_PREFIX}"
                    ));
                }
                if trimmed.len() < CLAUDE_SETUP_TOKEN_MIN_LENGTH {
                    return Err("Token looks too short; paste the full setup-token".into());
                }
                Ok(())
            })
            .interact_text()
            .context("Failed to read Claude setup token from terminal")?;
        normalize_claude_setup_token(&token)?
    };

    Ok(ImportedOAuthCredential {
        target_provider: "anthropic",
        default_profile_id: "anthropic-claude-oauth-default",
        default_label: "Setup token (claude)",
        source_name: "claude",
        access_token,
        refresh_token: None,
    })
}

/// Import cached Claude OAuth credentials from environment variables.
///
/// # Errors
///
/// Returns an error if the cached token fails validation.
pub(crate) fn import_claude_oauth_cached() -> Result<Option<ImportedOAuthCredential>> {
    let setup_token = std::env::var("ASTEREL_CLAUDE_SETUP_TOKEN")
        .ok()
        .or_else(|| std::env::var("ANTHROPIC_OAUTH_TOKEN").ok())
        .and_then(|value| {
            let trimmed = value.trim().to_string();
            (!trimmed.is_empty()).then_some(trimmed)
        });

    let Some(token) = setup_token else {
        return Ok(None);
    };

    let access_token = normalize_claude_setup_token(&token)?;

    Ok(Some(ImportedOAuthCredential {
        target_provider: "anthropic",
        default_profile_id: "anthropic-claude-oauth-default",
        default_label: "Setup token (claude)",
        source_name: "claude",
        access_token,
        refresh_token: None,
    }))
}

/// Import cached OAuth credentials by provider selector.
///
/// # Errors
///
/// Returns an error when provider-specific cached credential loading fails.
pub(crate) fn import_cached_oauth_credential_for_provider(
    provider: &str,
) -> Result<Option<ImportedOAuthCredential>> {
    OAuthProvider::parse(provider)?.import_cached_credential()
}

/// Import cached OAuth credentials by persisted OAuth source name.
///
/// # Errors
///
/// Returns an error when provider-specific cached credential loading fails.
pub(crate) fn import_cached_oauth_credential_for_source(
    source: &str,
) -> Result<Option<ImportedOAuthCredential>> {
    Ok(match OAuthProvider::parse_source(source) {
        Some(provider) => provider.import_cached_credential()?,
        None => None,
    })
}

/// Import OAuth credentials interactively for a provider selector.
///
/// # Errors
///
/// Returns an error when provider-specific interactive credential loading fails.
pub(crate) fn import_interactive_oauth_credential_for_provider(
    provider: &str,
    security: &SecurityPolicy,
) -> Result<Option<ImportedOAuthCredential>> {
    Ok(Some(
        OAuthProvider::parse(provider)?.import_interactive_credential(security)?,
    ))
}

fn normalize_claude_setup_token(token: &str) -> Result<String> {
    let trimmed = token.trim();
    if trimmed.is_empty() {
        bail!("Claude setup token cannot be empty");
    }
    if !trimmed.starts_with(CLAUDE_SETUP_TOKEN_PREFIX) {
        bail!(
            "Claude setup token must start with '{CLAUDE_SETUP_TOKEN_PREFIX}'. \
             Run `claude setup-token` first"
        );
    }
    if trimmed.len() < CLAUDE_SETUP_TOKEN_MIN_LENGTH {
        bail!("Claude setup token looks too short; paste the full setup-token");
    }
    Ok(trimmed.to_string())
}

fn run_interactive_command(
    bin: &str,
    args: &[&str],
    security: &SecurityPolicy,
    route_marker: &str,
) -> Result<()> {
    enforce_spawn_policy(
        security,
        bin,
        route_marker,
        ProcessSpawnClass::OperatorPlane,
    )?;

    let status = Command::new(bin)
        .args(args)
        .stdin(Stdio::inherit())
        .stdout(Stdio::inherit())
        .stderr(Stdio::inherit())
        .status()
        .with_context(|| format!("Failed to run `{bin}`"))?;

    if !status.success() {
        bail!(
            "Command `{bin} {}` failed with status {status}",
            args.join(" ")
        );
    }

    Ok(())
}

/// Query the Codex CLI for the current login status.
///
/// # Errors
///
/// Returns an error if the Codex CLI is not allowlisted or fails.
pub(crate) fn codex_login_status(security: &SecurityPolicy) -> Result<String> {
    enforce_spawn_policy(
        security,
        "codex",
        ROUTE_OAUTH_CODEX_STATUS,
        ProcessSpawnClass::OperatorPlane,
    )?;

    let output = Command::new("codex")
        .args(["login", "status"])
        .output()
        .context("Failed to run `codex login status`")?;

    if !output.status.success() {
        bail!("`codex login status` returned non-zero status");
    }

    let stdout = String::from_utf8_lossy(&output.stdout);
    Ok(stdout.trim().to_string())
}

/// Parsed output of `claude auth status --json`.
#[derive(Debug, Deserialize)]
pub(crate) struct ClaudeAuthStatus {
    /// Whether the user is currently logged in.
    #[serde(rename = "loggedIn")]
    pub(crate) logged_in: bool,
    /// Authentication method used (e.g., "oauth", "api-key").
    #[serde(rename = "authMethod")]
    pub(crate) auth_method: Option<String>,
}

/// Query the Claude CLI for the current auth status.
///
/// # Errors
///
/// Returns an error if the Claude CLI is not allowlisted or fails.
pub(crate) fn claude_auth_status(security: &SecurityPolicy) -> Result<ClaudeAuthStatus> {
    enforce_spawn_policy(
        security,
        "claude",
        ROUTE_OAUTH_CLAUDE_STATUS,
        ProcessSpawnClass::OperatorPlane,
    )?;

    let output = Command::new("claude")
        .args(["auth", "status", "--json"])
        .output()
        .context("Failed to run `claude auth status --json`")?;

    if !output.status.success() {
        bail!("`claude auth status --json` returned non-zero status");
    }

    let stdout = String::from_utf8_lossy(&output.stdout);
    serde_json::from_str(&stdout).context("Failed to parse claude auth status JSON")
}

/// Deserialized structure of `~/.codex/auth.json`.
#[derive(Debug, Deserialize)]
pub(crate) struct CodexAuthFile {
    #[serde(default)]
    pub(crate) tokens: Option<CodexAuthTokens>,
}

/// Token block from the Codex auth JSON file.
#[derive(Debug, Deserialize)]
pub(crate) struct CodexAuthTokens {
    /// OAuth access token for API calls.
    #[serde(default)]
    pub(crate) access_token: Option<String>,
    /// OAuth refresh token for token renewal.
    #[serde(default)]
    pub(crate) refresh_token: Option<String>,
}

fn codex_api_credential(auth_file: &CodexAuthFile) -> Option<String> {
    auth_file
        .tokens
        .as_ref()
        .and_then(|tokens| tokens.access_token.as_deref())
        .map(str::trim)
        .filter(|token| !token.is_empty())
        .map(ToOwned::to_owned)
}

fn codex_refresh_token(auth_file: &CodexAuthFile) -> Option<String> {
    auth_file
        .tokens
        .as_ref()
        .and_then(|tokens| tokens.refresh_token.as_deref())
        .map(str::trim)
        .filter(|token| !token.is_empty())
        .map(ToOwned::to_owned)
}

/// Load and parse `~/.codex/auth.json`.
///
/// # Errors
///
/// Returns an error if the file cannot be read or parsed.
pub(crate) fn load_codex_auth_file() -> Result<CodexAuthFile> {
    let home = UserDirs::new()
        .map(|u| u.home_dir().to_path_buf())
        .context("Could not resolve home directory")?;
    let path = home.join(".codex").join("auth.json");

    let content = fs::read_to_string(&path)
        .with_context(|| format!("Failed to read Codex auth file: {}", path.display()))?;
    serde_json::from_str(&content)
        .with_context(|| format!("Failed to parse Codex auth file: {}", path.display()))
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::security::SecurityPolicy;

    #[test]
    fn normalize_claude_setup_token_rejects_non_setup_token() {
        let err = normalize_claude_setup_token("sk-ant-api-key").unwrap_err();
        assert!(err.to_string().contains("sk-ant-oat01"));
    }

    #[test]
    fn normalize_claude_setup_token_rejects_too_short() {
        let short = format!("sk-ant-oat01-{}", "a".repeat(30));
        let err = normalize_claude_setup_token(&short).unwrap_err();
        assert!(err.to_string().contains("too short"));
    }

    #[test]
    fn normalize_claude_setup_token_accepts_valid_token() {
        let valid = format!("sk-ant-oat01-{}", "a".repeat(80));
        let result = normalize_claude_setup_token(&valid).unwrap();
        assert_eq!(result, valid);
    }

    #[test]
    fn codex_auth_json_parses_access_and_refresh_tokens() {
        let parsed: CodexAuthFile = serde_json::from_str(
            r#"{
  "tokens": {
    "access_token": "acc-123",
    "refresh_token": "ref-456"
  }
}"#,
        )
        .unwrap();

        let tokens = parsed.tokens.unwrap();
        assert_eq!(tokens.access_token.as_deref(), Some("acc-123"));
        assert_eq!(tokens.refresh_token.as_deref(), Some("ref-456"));
    }

    #[test]
    fn codex_api_credential_reads_access_token() {
        let parsed: CodexAuthFile = serde_json::from_str(
            r#"{
  "tokens": {
    "access_token": "acc-123",
    "refresh_token": "ref-456"
  }
}"#,
        )
        .unwrap();

        assert_eq!(codex_api_credential(&parsed).as_deref(), Some("acc-123"));
        assert_eq!(codex_refresh_token(&parsed).as_deref(), Some("ref-456"));
    }

    #[test]
    fn codex_api_credential_ignores_legacy_openai_api_key() {
        let parsed: CodexAuthFile = serde_json::from_str(
            r#"{
  "OPENAI_API_KEY": "sk-cli-generated"
}"#,
        )
        .unwrap();

        assert_eq!(
            codex_api_credential(&parsed),
            None,
            "OPENAI_API_KEY should not be used as credential source"
        );
    }

    #[test]
    fn codex_login_status_blocks_when_not_allowlisted() {
        let policy = SecurityPolicy {
            allowed_commands: vec!["git".to_string()],
            ..SecurityPolicy::default()
        };
        let err = codex_login_status(&policy).expect_err("codex should be policy-blocked");
        assert!(err.to_string().contains("not allowlisted"));
    }

    #[test]
    fn claude_auth_status_blocks_when_not_allowlisted() {
        let policy = SecurityPolicy {
            allowed_commands: vec!["git".to_string()],
            ..SecurityPolicy::default()
        };
        let err = claude_auth_status(&policy).expect_err("claude should be policy-blocked");
        assert!(err.to_string().contains("not allowlisted"));
    }
}
