/* eslint-disable */

// Auto-generated by scripts/dev/generate_admin_contract_ts.py. Do not edit by hand.

export const ADMIN_PATHS = {
  adminActivity: "/admin/v1/activity",
  adminAgents: "/admin/v1/agents",
  adminAuthProfilePatch: "/admin/v1/auth/profiles/{id}",
  adminAuthProfiles: "/admin/v1/auth/profiles",
  adminChannelAction: "/admin/v1/channels/{channel_id}/actions",
  adminChannelCreate: "/admin/v1/channels",
  adminChannelPatch: "/admin/v1/channels/{channel_id}",
  adminChannels: "/admin/v1/channels",
  adminCompanionCaptions: "/admin/v1/companions/{scope}/captions",
  adminCompanionIngress: "/admin/v1/companions/{scope}/ingress",
  adminCompanionWidgets: "/admin/v1/companions/{scope}/widgets",
  adminCompanionWindowCancel: "/admin/v1/companions/{scope}/windows/{window_id}/cancel",
  adminCompanionWindowConfirm: "/admin/v1/companions/{scope}/windows/{window_id}/confirm",
  adminCompanionWindows: "/admin/v1/companions/{scope}/windows",
  adminCompanions: "/admin/v1/companions",
  adminCompanionsPatch: "/admin/v1/companions",
  adminCronJobCreate: "/admin/v1/cron/jobs",
  adminCronJobDelete: "/admin/v1/cron/jobs/{job_id}",
  adminCronJobPatch: "/admin/v1/cron/jobs/{job_id}",
  adminCronJobRun: "/admin/v1/cron/jobs/{job_id}/run",
  adminCronJobs: "/admin/v1/cron/jobs",
  adminGatewayRestart: "/admin/v1/gateway/restart",
  adminGovernance: "/admin/v1/governance",
  adminMemoryCheckpoint: "/admin/v1/memory/checkpoint",
  adminMemoryConsolidation: "/admin/v1/memory/consolidation",
  adminMemoryCorrect: "/admin/v1/memory/correct",
  adminMemoryEntities: "/admin/v1/memory/entities",
  adminMemoryEntitySlots: "/admin/v1/memory/entities/{entity_id}/slots",
  adminMemoryExposure: "/admin/v1/memory/exposure",
  adminMemoryForget: "/admin/v1/memory/forget",
  adminMemorySelfAmendmentApprove: "/admin/v1/memory/self-amendments/approve",
  adminMemorySelfAmendments: "/admin/v1/memory/self-amendments",
  adminMood: "/admin/v1/mood",
  adminOpenApi: "/admin/v1/openapi.json",
  adminProviderPatch: "/admin/v1/providers/{id}",
  adminProviders: "/admin/v1/providers",
  adminProvidersPatch: "/admin/v1/providers",
  adminRuntime: "/admin/v1/runtime",
  adminSession: "/admin/v1/sessions/{session_id}",
  adminSessionCreate: "/admin/v1/sessions",
  adminSessionDelete: "/admin/v1/sessions/{session_id}",
  adminSessionMessageCreate: "/admin/v1/sessions/{session_id}/messages",
  adminSessionMessages: "/admin/v1/sessions/{session_id}/messages",
  adminSessions: "/admin/v1/sessions",
  adminSettings: "/admin/v1/settings",
  adminSettingsPatch: "/admin/v1/settings",
  adminSkillDelete: "/admin/v1/skills/{skill_id}",
  adminSkillInstall: "/admin/v1/skills/install",
  adminSkillPatch: "/admin/v1/skills/{skill_id}",
  adminSkills: "/admin/v1/skills",
  adminTenantContext: "/admin/v1/tenant-context",
  adminTenantContextSet: "/admin/v1/tenant-context",
  adminTenants: "/admin/v1/tenants",
  adminUpload: "/admin/v1/uploads",
  adminUsage: "/admin/v1/usage",
} as const;

export type AdminPathKey = keyof typeof ADMIN_PATHS;

export function adminPath(
  key: AdminPathKey,
  params: Record<string, string | number> = {},
): string {
  return ADMIN_PATHS[key].replace(/\{([^}]+)\}/g, (_match, name: string) => {
    const value = params[name];
    if (value === undefined || value === null) {
      throw new Error(`Missing admin path parameter '${name}' for ${key}`);
    }
    return encodeURIComponent(String(value));
  });
}

export interface ProblemDetails {
  type: string;
  title: string;
  status: number;
  detail: string;
  code: string;
}

export interface RuntimeStatus {
  status: "ok" | "degraded";
  version: string;
  model: string;
  db: {
    engine: string;
    status: string;
  };
  gateway: {
    ws_connections: number;
    max_ws_connections: number;
  };
  capabilities: {
    companion: boolean;
    governance: boolean;
    memory_review: boolean;
    channel_posture: boolean;
    session_review: boolean;
    a2a: boolean;
    multi_tenant: boolean;
  };
}

export interface UsageResponse {
  total_input_tokens: number;
  total_output_tokens: number;
  total_tokens: number;
  session_count: number;
  message_count: number;
  model: string;
}

export interface MoodResponse {
  label: string;
  confidence: number;
  description: string;
}

export interface ActivityEvent {
  kind: string;
  id: string;
  label: string;
  state: string;
  timestamp: string;
}

export interface ActivityTimelineResponse {
  events: Array<ActivityEvent>;
  count: number;
}

export interface Session {
  id: string;
  surface: string;
  owner_scope: string;
  state: string;
  created_at: string;
  updated_at: string;
}

export interface SessionListResponse {
  items: Array<Session>;
  next_cursor?: string;
}

export interface Message {
  id: string;
  role: string;
  content: string;
  input_tokens?: number;
  output_tokens?: number;
  created_at: string;
}

export interface SessionMessageListResponse {
  items: Array<Message>;
  next_cursor?: string;
}

export interface MemoryEntitySummary {
  entity_id: string;
  slot_count: number;
}

export interface MemoryEntitiesResponse {
  items: Array<MemoryEntitySummary>;
  count: number;
  backend: string;
}

export interface MemorySlotProvenance {
  source_class: string;
  reference: string;
  evidence_uri?: string;
}

export interface MemorySlotSummary {
  slot_key: string;
  value: string;
  source: string;
  confidence: number;
  importance: number;
  privacy_level: string;
  updated_at: string;
  provenance?: MemorySlotProvenance;
}

export interface MemorySlotsResponse {
  entity_id: string;
  items: Array<MemorySlotSummary>;
  count: number;
  event_count: number;
}

export interface MemoryConsolidationWorker {
  entity_id: string;
  checkpoint_event_count: number;
  phase: string;
  disposition?: string;
  previous_watermark?: number;
  applied_watermark?: number;
  started_at?: string;
  finished_at?: string;
  last_error?: string;
}

export interface MemoryConsolidationStatusResponse {
  items: Array<MemoryConsolidationWorker>;
  count: number;
}

export interface MemoryExposureStatusResponse {
  observed_builds: number;
  sensitive_counts_redacted: boolean;
}

export interface SelfAmendmentCandidateReview {
  candidate_id: string;
  kind: string;
  status: string;
  tenant_id?: string | null;
  person_id: string;
  surface: string;
  privacy: string;
  evidence_ids: Array<string>;
  reason: string;
  proposed_amendment: string;
  raw_payload_redacted: boolean;
}

export interface SelfAmendmentReviewResponse {
  count: number;
  items: Array<SelfAmendmentCandidateReview>;
  raw_payloads_redacted: boolean;
  durable_writes_enabled: boolean;
}

export interface SelfAmendmentApproveRequest {
  candidate_id: string;
  reason: string;
}

export interface SelfAmendmentApprovalResponse {
  status: string;
  candidate_id: string;
  entity_id: string;
  slot_key: string;
  event_id: string;
  persisted: boolean;
  raw_payload_redacted: boolean;
}

export interface AuthProfile {
  id: string;
  provider: string;
  auth_route?: string;
  label?: string;
  has_api_key: boolean;
  auth_scheme?: string;
  oauth_source?: string;
  disabled: boolean;
}

export interface AuthProfilesResponse {
  items: Array<AuthProfile>;
  defaults: Record<string, string>;
}

export interface ProvidersResponse {
  active_provider: string;
  active_model: string;
  temperature: number;
}

export interface SettingsResponse {
  workspace_dir: string;
  memory: {
    backend: string;
    auto_save: boolean;
  };
  autonomy: {
    max_tool_loop: number;
  };
  gateway: {
    pairing_enabled: boolean;
    defense_mode: string;
    cors_origins: Array<string>;
  };
}

export interface Channel {
  id: string;
  name: string;
  configured: boolean;
  type: string;
  enabled?: boolean;
}

export interface ChannelsResponse {
  items: Array<Channel>;
  active_names: Array<string>;
  high_freedom: boolean;
}

export interface SkillTool {
  name: string;
  description: string;
  kind: string;
}

export interface Skill {
  name: string;
  description: string;
  version: string;
  author?: string;
  tags: Array<string>;
  tools: Array<SkillTool>;
  location?: string;
  enabled?: boolean;
}

export interface SkillsResponse {
  items: Array<Skill>;
  count: number;
}

export interface CronJob {
  id: string;
  expression: string;
  command: string;
  next_run: string;
  last_run?: string;
  last_status?: string;
  job_kind: "user" | "agent";
  origin: "user" | "agent";
  expires_at?: string;
  max_attempts: number;
  consecutive_failures: number;
  breaker_open_until?: string;
  enabled?: boolean;
}

export interface CronJobListResponse {
  items: Array<CronJob>;
}

export interface CompanionScope {
  scope: string;
  captions: number;
  widgets: number;
  windows: number;
  context_gate_entries: number;
}

export interface CompanionScopeListResponse {
  items: Array<CompanionScope>;
  count: number;
}

export interface CompanionCaption {
  caption_id: string;
  channel: "speaker" | "assistant";
  sequence: number;
  text: string;
  emitted_at: string;
}

export interface CompanionCaptionListResponse {
  scope: string;
  items: Array<CompanionCaption>;
}

export interface CompanionWidget {
  widget_id: string;
  payload: Record<string, unknown>;
  created_at: string;
  updated_at: string;
  expires_at?: string;
}

export interface CompanionWidgetListResponse {
  scope: string;
  items: Array<CompanionWidget>;
}

export interface CompanionWindowEntry {
  window_id: string;
  requested_action: string;
  created_at: string;
  expires_at: string;
  state: "pending" | "confirmed" | "cancelled" | "expired";
}

export interface CompanionWindowListResponse {
  scope: string;
  items: Array<CompanionWindowEntry>;
}

export interface TenantRegistryRow {
  tenant_id: string;
  principal_hashes: Array<string>;
  binding_count: number;
  workspace_present: boolean;
}

export interface TenantsResponse {
  rows: Array<TenantRegistryRow>;
  discovered_workspaces: Array<string>;
  binding_count: number;
  workspace_count: number;
  tenant_scope?: string;
}

export interface TenantContextResponse {
  active_tenant?: string;
  tenant_header?: string;
  tenant_mode_available: boolean;
}

export interface TenantContextUpdateResponse {
  status: string;
  tenant_id?: string;
}

export interface DomainTrustEntry {
  domain: string;
  score: number;
  autonomy: string;
  success_count: number;
  violation_count: number;
  last_updated: string;
}

export interface PendingWindow {
  scope: string;
  window_id: string;
  requested_action: string;
  created_at: string;
  expires_at: string;
}

export interface GovernanceSummary {
  runtime: {
    memory_backend: string;
    memory_review: boolean;
    companion_surface_windows: number;
    companion_surface_scopes: number;
  };
  domain_trust: Array<DomainTrustEntry>;
  pending_windows: Array<PendingWindow>;
}

export interface AgentEntry {
  id: string;
  name: string;
  model: string;
  is_default: boolean;
  status: string;
  task?: string;
}

export interface AgentListResponse {
  items: Array<AgentEntry>;
  count: number;
}

export interface StatusResponse {
  status?: string;
  id?: string;
  name?: string;
  source?: string;
  result?: string;
  active_tenant?: string;
  event_id?: string;
  run_id?: string;
  [key: string]: unknown;
}
