//! Central types for the turn augmentation pipeline.
//!
//! Each subsystem (taste, memory, experience, affect) produces a
//! text block appended to the enriched user message and an optional
//! style overlay that adjusts per-turn rendering parameters.

use super::policy::{PolicyDecision, SituationFeatures};
use crate::core::affect::topology::TopologyDiffDiagnostic;
use crate::core::memory::influence::GroundingExposureProjection;

/// Aggregated augmentation output produced by the pre-answer pipeline.
///
/// Each block is an optional prompt-contract string generated by a
/// specific subsystem.  Empty blocks are omitted when rendering.
#[derive(Debug, Clone, Default)]
pub(crate) struct TurnAugmentations {
    /// Structured memory grounding contract (System 2).
    pub grounding_block: String,
    /// Structured public/private/secret exposure counts for grounding.
    pub grounding_exposure: GroundingExposureProjection,
    /// Taste-guided render contract (System 1).
    pub taste_block: String,
    /// Affect summary and response modulation guidance (System 6).
    pub affect_block: String,
    /// Retrieved experience hints from past outcomes (System 3).
    pub experience_block: String,
    /// Distilled principles from experience clusters.
    pub principle_block: String,
    /// Attention schema focus block.
    pub attention_block: String,
    /// Curiosity drive signal block.
    pub curiosity_block: String,
    /// Learned value guidance block.
    pub value_block: String,
    /// Lightweight Theory of Mind block (Phase 1-4).
    pub user_model_block: String,
    /// Integrated self/world/relationship model block.
    pub integrated_model_block: String,
    /// Affect cause guidance block (Phase 2-2).
    pub cause_guidance_block: String,
    /// Big Five personality guidance block.
    pub big_five_block: String,
    /// Unified behavior selector block.
    pub behavior_block: String,
    /// Per-turn style overlay derived from affect / taste signals.
    pub style_overlay: TurnStyleOverlay,
    /// Reasoning strategy guidance block injected into the prompt.
    pub reasoning_block: String,
    /// Cognitive scaffolding JSON snapshot.
    pub scaffolding_block: String,
    /// Desire-driven objective prefix block.
    pub desire_block: String,
    /// Affect topology snapshot: surfaced/suppressed nodes after diffusion and latent bias.
    pub topology_block: String,
    /// Structured diagnostics for base vs diffused vs surfaced topology activation.
    pub topology_diagnostics: Vec<TopologyDiffDiagnostic>,
    /// Session control state: conversational mode, density, and avoidance constraints.
    pub session_control_block: String,
    /// Situation features extracted for this turn (ADR-0010 Phase 2+).
    pub situation: SituationFeatures,
    /// Policy decision governing this turn (ADR-0010 Phase 2+).
    pub policy: PolicyDecision,
}

/// Bounded per-turn style deltas that are applied *on top of* the
/// canonical `StyleProfileState` for a single turn only.
///
/// All deltas are intentionally small and clamped before use.
/// They never mutate the persistent style profile.
#[derive(Debug, Clone, Copy, Default)]
#[allow(clippy::struct_field_names)] // _delta suffix distinguishes from absolute values
pub(crate) struct TurnStyleOverlay {
    /// Formality delta (clamped to ±15, matching `MAX_STYLE_SCORE_DELTA`).
    pub formality_delta: i8,
    /// Verbosity delta (clamped to ±15).
    pub verbosity_delta: i8,
    /// Temperature delta (clamped to ±0.15, matching `MAX_STYLE_TEMPERATURE_DELTA`).
    pub temperature_delta: f64,
}

impl TurnAugmentations {
    /// Returns `true` if any block contains non-empty content.
    pub(crate) fn has_content(&self) -> bool {
        !self.grounding_block.is_empty()
            || !self.taste_block.is_empty()
            || !self.affect_block.is_empty()
            || !self.experience_block.is_empty()
            || !self.principle_block.is_empty()
            || !self.attention_block.is_empty()
            || !self.curiosity_block.is_empty()
            || !self.value_block.is_empty()
            || !self.user_model_block.is_empty()
            || !self.integrated_model_block.is_empty()
            || !self.cause_guidance_block.is_empty()
            || !self.big_five_block.is_empty()
            || !self.behavior_block.is_empty()
            || !self.scaffolding_block.is_empty()
            || !self.desire_block.is_empty()
            || !self.topology_block.is_empty()
            || !self.session_control_block.is_empty()
    }
}

/// Apply augmentation blocks to the enriched user message.
///
/// If no blocks have content, returns the input unchanged (no allocation).
#[cfg(test)]
pub(crate) fn apply_augmentation_blocks(
    enriched: &str,
    augmentations: &TurnAugmentations,
) -> String {
    let blocks = crate::core::agent::presenter::render_blocks(augmentations);
    if blocks.is_empty() {
        enriched.to_string()
    } else {
        format!("{enriched}\n\n{blocks}")
    }
}

/// Budget-aware variant of [`apply_augmentation_blocks`].
pub(crate) fn apply_augmentation_blocks_budgeted(
    enriched: &str,
    augmentations: &TurnAugmentations,
    budget: &super::cognitive_budget::AugmentationBudget,
) -> String {
    if !augmentations.topology_diagnostics.is_empty() {
        tracing::trace!(
            diagnostics = augmentations.topology_diagnostics.len(),
            "affect topology diagnostics available for this turn"
        );
    }
    if !augmentations.grounding_exposure.is_empty() {
        tracing::trace!(
            public_visible = augmentations.grounding_exposure.public_visible,
            private_internal = augmentations.grounding_exposure.private_internal,
            secret_suppressed = augmentations.grounding_exposure.secret_suppressed,
            "memory grounding exposure diagnostics available for this turn"
        );
    }
    let blocks = crate::core::agent::presenter::render_blocks_budgeted(augmentations, budget);
    if blocks.is_empty() {
        enriched.to_string()
    } else {
        let mut out = String::with_capacity(enriched.len() + 2 + blocks.len());
        out.push_str(enriched);
        out.push_str("\n\n");
        out.push_str(&blocks);
        out
    }
}

impl TurnStyleOverlay {
    /// Clamp all deltas to their constitutional guardrail bounds.
    #[must_use]
    pub(crate) fn clamped(self) -> Self {
        const MAX_SCORE_DELTA: i8 = 15;
        const MAX_TEMPERATURE_DELTA: f64 = 0.15;
        Self {
            formality_delta: self
                .formality_delta
                .clamp(-MAX_SCORE_DELTA, MAX_SCORE_DELTA),
            verbosity_delta: self
                .verbosity_delta
                .clamp(-MAX_SCORE_DELTA, MAX_SCORE_DELTA),
            temperature_delta: self
                .temperature_delta
                .clamp(-MAX_TEMPERATURE_DELTA, MAX_TEMPERATURE_DELTA),
        }
    }

    /// Returns `true` if all deltas are zero (no adjustment).
    pub(crate) fn is_zero(&self) -> bool {
        self.formality_delta == 0 && self.verbosity_delta == 0 && self.temperature_delta == 0.0
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn default_augmentations_have_no_content() {
        let aug = TurnAugmentations::default();
        assert!(!aug.has_content());
        assert!(crate::core::agent::presenter::render_blocks(&aug).is_empty());
    }

    #[test]
    fn augmentations_render_non_empty_blocks() {
        let aug = TurnAugmentations {
            grounding_block: "[Grounding]".to_string(),
            taste_block: String::new(),
            affect_block: "[Affect]".to_string(),
            experience_block: String::new(),
            ..Default::default()
        };
        assert!(aug.has_content());
        assert_eq!(
            crate::core::agent::presenter::render_blocks(&aug),
            "[Grounding]\n\n[Affect]"
        );
    }

    #[test]
    fn apply_blocks_no_content_returns_input() {
        let aug = TurnAugmentations::default();
        let result = apply_augmentation_blocks("hello", &aug);
        assert_eq!(result, "hello");
    }

    #[test]
    fn apply_blocks_appends_content() {
        let aug = TurnAugmentations {
            taste_block: "[Taste contract]".to_string(),
            topology_block: "[Topology]".to_string(),
            session_control_block: "[Session Control]".to_string(),
            ..Default::default()
        };
        let result = apply_augmentation_blocks("hello", &aug);
        assert_eq!(
            result,
            "hello\n\n[Taste contract]\n\n[Topology]\n\n[Session Control]"
        );
    }

    #[test]
    fn style_overlay_clamp_respects_bounds() {
        let overlay = TurnStyleOverlay {
            formality_delta: 50,
            verbosity_delta: -30,
            temperature_delta: 0.5,
        };
        let clamped = overlay.clamped();
        assert_eq!(clamped.formality_delta, 15);
        assert_eq!(clamped.verbosity_delta, -15);
        assert!((clamped.temperature_delta - 0.15).abs() < f64::EPSILON);
    }

    #[test]
    fn default_overlay_is_zero() {
        let overlay = TurnStyleOverlay::default();
        assert!(overlay.is_zero());
    }
}
