#!/usr/bin/env bash
set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
PROJECT_ROOT="$(dirname "$(dirname "$SCRIPT_DIR")")"
SRC_DIR="$PROJECT_ROOT/src"
OUTPUT_DIR="$PROJECT_ROOT/target/architecture"
DOT_FILE="$OUTPUT_DIR/dependency-graph.dot"
EDGES_FILE="$OUTPUT_DIR/dependency-edges.md"

mkdir -p "$OUTPUT_DIR"

VIOLATIONS=0
WORDING_VIOLATIONS=0

##############################################################################
# 1. Generate dependency graph (DOT + markdown edges)
##############################################################################

if command -v cargo-modules &>/dev/null; then
    echo "==> Extracting dependency graph..."
    cargo modules dependencies --lib --no-externs --no-fns --no-types --no-traits \
        >"$DOT_FILE" 2>/dev/null

    # cargo-modules can resolve this re-exported Provider trait dependency
    # differently across Rust patch releases. Keep generated artifacts stable by
    # omitting the transitive edge; core::providers::traits owns the real import.
    perl -0pi -e 's/^\s*"asterel::transport::channels::startup::runtime" -> "asterel::contracts::provider" \[label="uses".*\n//m' "$DOT_FILE"

    {
        printf "# Dependency Edges\n\n"
        printf "> Auto-generated by \`scripts/dev/check_architecture.sh\`. Do not edit.\n\n"
        printf "| From | To | Type |\n"
        printf "|------|-----|------|\n"

        grep '\->' "$DOT_FILE" | grep '"uses"' |
            perl -ne 'if (/"(asterel(?:::[^"]*)?)"\s*->\s*"(asterel::[^"]*)".*label="uses"/) { print "$1 $2\n"; }' |
            sed 's/asterel:://g' |
            LC_ALL=C sort -u |
            while read -r from to; do
                printf "| \`%s\` | \`%s\` | uses |\n" "$from" "$to"
            done
    } >"$EDGES_FILE"

    edge_count=$(grep -c "^|" "$EDGES_FILE" || true)
    echo "   Generated: $DOT_FILE"
    echo "   Generated: $EDGES_FILE ($((edge_count - 2)) dependency edges)"
else
    echo "WARN: cargo-modules not installed, skipping dependency graph"
    echo "      Install: cargo install cargo-modules"
    {
        printf "# Dependency Edges\n\n"
        printf "> Auto-generated by \`scripts/dev/check_architecture.sh\`. Do not edit.\n\n"
        printf "> Dependency extraction skipped: \`cargo-modules\` is not installed in this environment.\n"
    } >"$EDGES_FILE"
    rm -f "$DOT_FILE"
fi

##############################################################################
# 2. C1 constraint enforcement — forbidden dependency edges
##############################################################################

echo "==> Checking C1 dependency direction constraints..."

check_forbidden_dep() {
    local from_pattern="$1"
    local to_pattern="$2"
    local rule_desc="$3"

    if [[ ! -f "$DOT_FILE" ]]; then return; fi

    local found
    found=$(grep '\->' "$DOT_FILE" | grep '"uses"' |
        sed -n 's/.*"\(asterel::[^"]*\)"[[:space:]]*->[[:space:]]*"\(asterel::[^"]*\)".*/\1 \2/p' |
        while read -r src dst; do
            local src_short="${src#asterel::}"
            local dst_short="${dst#asterel::}"
            if [[ "$src_short" == $from_pattern* ]] && [[ "$dst_short" == $to_pattern* ]]; then
                echo "  $src_short -> $dst_short"
            fi
        done || true)

    if [[ -n "$found" ]]; then
        echo "VIOLATION [$rule_desc]:"
        echo "$found"
        VIOLATIONS=$((VIOLATIONS + 1))
    fi
}

for l0_mod in contracts config utils; do
    l0_violations=$(grep -rn "use crate::core\|use crate::security\|use crate::transport\|use crate::platform\|use crate::plugins\|use crate::runtime\|use crate::simulation\|use crate::media\|use crate::cli\|use crate::onboard\|use crate::ui" \
        "$SRC_DIR/$l0_mod/" 2>/dev/null | grep -v "#\[cfg(test)\]" | grep -v "^.*tests\.rs:" || true)
    if [[ -n "$l0_violations" ]]; then
        echo "VIOLATION [C1: L0($l0_mod) imports upper layers]:"
        echo "$l0_violations" | while IFS= read -r line; do
            echo "  ${line#$SRC_DIR/}"
        done
        VIOLATIONS=$((VIOLATIONS + 1))
    fi
done

for l1_dir in core/memory core/persona core/providers core/sessions core/subagents core/experience core/eval; do
    if [[ ! -d "$SRC_DIR/$l1_dir" ]]; then continue; fi
    l1_violations=$(grep -rn "use crate::transport\|use crate::ui\|use crate::cli\|use crate::onboard\|use crate::platform::service\|use crate::runtime::diagnostics\|use crate::plugins::companion" \
        "$SRC_DIR/$l1_dir/" 2>/dev/null | grep -v "^.*tests\.rs:" || true)
    if [[ -n "$l1_violations" ]]; then
        echo "VIOLATION [C1: L1($l1_dir) imports surface layers]:"
        echo "$l1_violations" | while IFS= read -r line; do
            echo "  ${line#$SRC_DIR/}"
        done
        VIOLATIONS=$((VIOLATIONS + 1))
    fi
done

echo "   C1 violations found: $VIOLATIONS"

##############################################################################
# 3. Active-surface wording drift — deleted planner terminology must not return
##############################################################################

echo "==> Checking active-surface wording drift..."

check_forbidden_wording() {
    local file="$1"
    local pattern="$2"
    local desc="$3"
    local matches
    matches=$(grep -n "$pattern" "$file" 2>/dev/null || true)
    if [[ -z "$matches" ]]; then return; fi

    echo "VIOLATION [wording: $desc]:"
    echo "$matches" | while IFS= read -r line; do
        echo "  ${file#$PROJECT_ROOT/}:$line"
    done
    WORDING_VIOLATIONS=$((WORDING_VIOLATIONS + 1))
}

for wording in \
    "Plan inbox" \
    "Pending plans" \
    "Autonomy plans" \
    "selected plan" \
    "plan approvals" \
    "high plan failure rate"; do
    check_forbidden_wording "$PROJECT_ROOT/desktop/src/locales/en.json" "$wording" "desktop locale drift"
    check_forbidden_wording "$PROJECT_ROOT/desktop/src/locales/ja.json" "$wording" "desktop locale drift"
done

for forbidden in \
    '/lab/' \
    'routes/lab/' \
    '/admin/v1/a2a/tasks' \
    '/admin/v1/evolution/'; do
    check_forbidden_wording "$PROJECT_ROOT/desktop/src/routeTree.gen.ts" "$forbidden" "removed desktop lab surface drift"
    check_forbidden_wording "$PROJECT_ROOT/desktop/src/components/sidebar.tsx" "$forbidden" "removed desktop lab surface drift"
    check_forbidden_wording "$PROJECT_ROOT/desktop/src/routes/__root.tsx" "$forbidden" "removed desktop lab surface drift"
    check_forbidden_wording "$PROJECT_ROOT/src/transport/gateway/admin_contract.json" "$forbidden" "removed admin lab surface drift"
done

echo "   Wording violations found: $WORDING_VIOLATIONS"

##############################################################################
# 4. Module existence drift — design doc references vs filesystem
##############################################################################

echo "==> Checking module existence drift..."

DESIGN_DOC="$PROJECT_ROOT/docs/src/content/docs/architecture/layers.md"
DRIFT_FILE="$OUTPUT_DIR/drift-report.md"
DRIFT_COUNT=0

# Paths referenced in the design doc as aspirational (将来的には) that do not exist yet.
# These are intentional future targets, not drift errors.
ASPIRATIONAL_PATHS=("src/application" "src/control")

{
    printf "# Architecture Drift Report\n\n"
    printf "> Auto-generated by \`scripts/dev/check_architecture.sh\`. Do not edit.\n\n"

    if [[ -f "$DESIGN_DOC" ]]; then
        printf "## Module References in Design Docs\n\n"
        printf "| Referenced Path | Exists | Status |\n"
        printf "|----------------|--------|--------|\n"

        refs=$(grep -oP 'src/[a-z_/]+[a-z]' "$DESIGN_DOC" | sort -u | grep -v '^src/$' | grep -v '\*')
        for ref_path in $refs; do
            if [[ "$ref_path" =~ _$ ]]; then continue; fi
            skip=false
            for asp in "${ASPIRATIONAL_PATHS[@]}"; do
                if [[ "$ref_path" == "$asp" ]]; then
                    skip=true
                    break
                fi
            done
            if [[ "$skip" == "true" ]]; then
                printf "| \`%s\` | — | aspirational |\n" "$ref_path"
                continue
            fi
            full_path="$PROJECT_ROOT/$ref_path"
            has_glob_match=$(ls "${full_path}"* 2>/dev/null | head -1 || true)
            if [[ -d "$full_path" || -f "$full_path" || -f "${full_path}.rs" || -f "${full_path}.json" || -n "$has_glob_match" ]]; then
                printf "| \`%s\` | ✓ | exists |\n" "$ref_path"
            else
                printf "| \`%s\` | ✗ | **missing** |\n" "$ref_path"
                DRIFT_COUNT=$((DRIFT_COUNT + 1))
            fi
        done

        printf "\n"
    fi

    printf "## Stub / Placeholder Detection\n\n"
    printf "| File | Pattern | Line |\n"
    printf "|------|---------|------|\n"

    grep -rn 'todo!()' "$SRC_DIR" --include="*.rs" 2>/dev/null | head -20 |
        while IFS=: read -r file line content; do
            rel="${file#$PROJECT_ROOT/}"
            printf "| \`%s\` | todo!() | L%s |\n" "$rel" "$line"
        done || true

    grep -rn 'unimplemented!()' "$SRC_DIR" --include="*.rs" 2>/dev/null | head -20 |
        while IFS=: read -r file line content; do
            rel="${file#$PROJECT_ROOT/}"
            printf "| \`%s\` | unimplemented!() | L%s |\n" "$rel" "$line"
        done || true

    printf "\n---\n\n"
    printf "**Module drift**: %d missing references\n" "$DRIFT_COUNT"
    printf "**C1 violations**: %d\n" "$VIOLATIONS"
    printf "**Active-surface wording violations**: %d\n" "$WORDING_VIOLATIONS"

} >"$DRIFT_FILE"

echo "   Generated: $DRIFT_FILE"
echo "   Module drift: $DRIFT_COUNT missing references"

##############################################################################
# Summary
##############################################################################

echo ""
echo "=== Architecture Check Summary ==="
echo "  Dependency edges: $(grep -c '"uses"' "$DOT_FILE" 2>/dev/null || echo 'N/A')"
echo "  C1 violations:    $VIOLATIONS"
echo "  Wording drift:    $WORDING_VIOLATIONS"
echo "  Module drift:     $DRIFT_COUNT"

if [[ $VIOLATIONS -gt 0 || $WORDING_VIOLATIONS -gt 0 ]]; then
    echo ""
    echo "FAILED: architecture guardrails detected drift"
    exit 1
fi

echo ""
echo "PASSED: All architecture checks green"
