#!/usr/bin/env bash
set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
PROJECT_ROOT="$(dirname "$(dirname "$SCRIPT_DIR")")"
SRC_DIR="$PROJECT_ROOT/src"
OUTPUT_DIR="$PROJECT_ROOT/target/architecture"
OUTPUT_FILE="$OUTPUT_DIR/module-map.md"

mkdir -p "$OUTPUT_DIR"

assign_layer() {
    local path="$1"
    case "$path" in
    contracts | contracts/*) echo "L0" ;;
    config | config/*) echo "L0" ;;
    core/memory | core/memory/*) echo "L1" ;;
    core/persona | core/persona/*) echo "L1" ;;
    core/inference | core/inference/*) echo "L1" ;;
    core/providers | core/providers/*) echo "L1" ;;
    core/sessions | core/sessions/*) echo "L1" ;;
    core/subagents | core/subagents/*) echo "L1" ;;
    core/experience | core/experience/*) echo "L1" ;;
    core/eval | core/eval/*) echo "L1" ;;
    core/taste | core/taste/*) echo "L1" ;;
    core/tools | core/tools/*) echo "L2" ;;
    security | security/*) echo "L2" ;;
    core/agent | core/agent/*) echo "L3" ;;
    core/affect | core/affect/*) echo "L3" ;;
    core) echo "L1-L3" ;;
    runtime/services | runtime/services/*) echo "L4" ;;
    runtime/diagnostics | runtime/diagnostics/*) echo "L4" ;;
    runtime/trust_tracker | runtime/trust_tracker/*) echo "L4" ;;
    runtime/observability | runtime/observability/*) echo "L4" ;;
    runtime/usage | runtime/usage/*) echo "L4" ;;
    runtime/environment | runtime/environment/*) echo "L4" ;;
    runtime) echo "L4" ;;
    transport/gateway | transport/gateway/*) echo "L5" ;;
    transport/channels | transport/channels/*) echo "L5" ;;
    transport) echo "L5" ;;
    cli | cli/*) echo "L5" ;;
    platform | platform/*) echo "L5" ;;
    ui | ui/*) echo "L5" ;;
    plugins | plugins/*) echo "L5" ;;
    onboard | onboard/*) echo "L5" ;;
    runtime/tunnel | runtime/tunnel/*) echo "L5" ;;
    media | media/*) echo "L3" ;;
    utils | utils/*) echo "L0" ;;
    *) echo "—" ;;
    esac
}

extract_doc_comment() {
    local file="$1"
    local doc=""
    while IFS= read -r line; do
        if [[ "$line" =~ ^//![[:space:]]*(.*) ]]; then
            local content="${BASH_REMATCH[1]}"
            if [[ -n "$doc" ]]; then
                doc="$doc $content"
            else
                doc="$content"
            fi
        elif [[ "$line" =~ ^//!$ ]]; then
            continue
        else
            break
        fi
    done <"$file"
    if [[ ${#doc} -gt 120 ]]; then
        doc="${doc:0:117}..."
    fi
    echo "$doc"
}

{
    printf "# Module Map\n\n"
    printf "> Auto-generated by \`scripts/dev/generate_module_map.sh\`. Do not edit.\n"
    printf "> Re-generate: \`./scripts/dev/generate_module_map.sh\`\n"
    printf "> Authority: layer assignment follows the public architecture docs and executable source; descriptions are extracted from source doc comments and may expose stale prose if the source comment drifts.\n\n"
    printf "| Module | Layer | Description |\n"
    printf "|--------|-------|-------------|\n"

    find "$SRC_DIR" -name "mod.rs" -type f | sort | while read -r modfile; do
        rel="${modfile#$SRC_DIR/}"
        module_path="${rel%/mod.rs}"

        if [[ "$module_path" == "mod.rs" ]]; then
            continue
        fi

        layer=$(assign_layer "$module_path")
        doc=$(extract_doc_comment "$modfile")

        if [[ -z "$doc" ]]; then
            doc="*(no doc comment)*"
        fi

        printf "| \`%s\` | %s | %s |\n" "$module_path" "$layer" "$doc"
    done

    printf "\n---\n\n"

    total=$(find "$SRC_DIR" -name "mod.rs" -type f | wc -l)
    documented=$(find "$SRC_DIR" -name "mod.rs" -type f -exec grep -l '^//!' {} \; | wc -l)
    printf "**Coverage**: %d/%d modules documented (%d%%)\n" "$documented" "$total" $((documented * 100 / total))

} >"$OUTPUT_FILE"

echo "Generated: $OUTPUT_FILE"
echo "Modules: $(grep -c '^\|' "$OUTPUT_FILE" || true) rows"
