#!/usr/bin/env python3
"""Generate desktop TypeScript helpers from the admin OpenAPI contract."""

from __future__ import annotations

import json
import re
from pathlib import Path


ROOT = Path(__file__).resolve().parents[2]
CONTRACT_PATH = ROOT / "src/transport/gateway/admin_contract.json"
OUTPUT_PATH = ROOT / "desktop/src/lib/admin-contract.generated.ts"


def load_contract() -> dict:
    return json.loads(CONTRACT_PATH.read_text())


def ref_name(ref: str) -> str:
    return ref.rsplit("/", 1)[-1]


def is_identifier(name: str) -> bool:
    return name.isidentifier() and not name.startswith("__")


def quote(value: str) -> str:
    return json.dumps(value, ensure_ascii=False)


def ts_type(schema: dict | bool | None, indent: int = 0) -> str:
    if schema is None:
        return "unknown"
    if schema is True:
        return "unknown"
    if schema is False:
        return "never"
    if "$ref" in schema:
        return ref_name(schema["$ref"])
    if "enum" in schema:
        return " | ".join(quote(str(value)) for value in schema["enum"])

    schema_type = schema.get("type")
    if isinstance(schema_type, list):
        members = [
            ts_type({**schema, "type": member}, indent)
            for member in schema_type
            if member != "null"
        ]
        if "null" in schema_type:
            members.append("null")
        return " | ".join(dict.fromkeys(members)) or "unknown"

    if (
        schema_type == "object"
        or "properties" in schema
        or "additionalProperties" in schema
    ):
        properties = schema.get("properties", {})
        required = set(schema.get("required", []))
        additional = schema.get("additionalProperties")
        if not properties and additional is not None:
            return f"Record<string, {ts_type(additional, indent)}>"

        lines: list[str] = ["{"]
        next_indent = " " * (indent + 2)
        for prop_name, prop_schema in properties.items():
            key = prop_name if is_identifier(prop_name) else quote(prop_name)
            optional = "" if prop_name in required else "?"
            lines.append(
                f"{next_indent}{key}{optional}: {ts_type(prop_schema, indent + 2)};"
            )
        if additional is True:
            lines.append(f"{next_indent}[key: string]: unknown;")
        elif isinstance(additional, dict):
            lines.append(
                f"{next_indent}[key: string]: {ts_type(additional, indent + 2)};"
            )
        lines.append(" " * indent + "}")
        return "\n".join(lines)

    if schema_type == "array":
        return f"Array<{ts_type(schema.get('items', {}), indent)}>"
    if schema_type in {"integer", "number"}:
        return "number"
    if schema_type == "boolean":
        return "boolean"
    if schema_type == "string":
        return "string"
    return "unknown"


def emit_schema(name: str, schema: dict) -> str:
    rendered = ts_type(schema, 0)
    if rendered.startswith("{"):
        return f"export interface {name} {rendered}\n"
    return f"export type {name} = {rendered};\n"


def collect_paths(contract: dict) -> list[tuple[str, str]]:
    entries: list[tuple[str, str]] = []
    seen: set[str] = set()
    for path, methods in contract.get("paths", {}).items():
        for method_schema in methods.values():
            operation_id = method_schema.get("operationId")
            if operation_id is None:
                continue
            if operation_id in seen:
                raise SystemExit(f"duplicate admin operationId: {operation_id}")
            seen.add(operation_id)
            entries.append((operation_id, path))
    return sorted(entries)


def generate() -> str:
    contract = load_contract()
    schemas = contract.get("components", {}).get("schemas", {})
    path_entries = collect_paths(contract)

    parts = [
        "/* eslint-disable */",
        "",
        "// Auto-generated by scripts/dev/generate_admin_contract_ts.py. Do not edit by hand.",
        "",
        "export const ADMIN_PATHS = {",
    ]
    for operation_id, path in path_entries:
        parts.append(f"  {operation_id}: {quote(path)},")
    parts.extend(
        [
            "} as const;",
            "",
            "export type AdminPathKey = keyof typeof ADMIN_PATHS;",
            "",
            "export function adminPath(",
            "  key: AdminPathKey,",
            "  params: Record<string, string | number> = {},",
            "): string {",
            "  return ADMIN_PATHS[key].replace(/\\{([^}]+)\\}/g, (_match, name: string) => {",
            "    const value = params[name];",
            "    if (value === undefined || value === null) {",
            "      throw new Error(`Missing admin path parameter '${name}' for ${key}`);",
            "    }",
            "    return encodeURIComponent(String(value));",
            "  });",
            "}",
            "",
        ]
    )

    for name, schema in schemas.items():
        parts.append(emit_schema(name, schema).rstrip())
        parts.append("")

    return "\n".join(parts).rstrip() + "\n"


def main() -> None:
    OUTPUT_PATH.write_text(generate())


if __name__ == "__main__":
    main()
